apiVersion: v1
kind: Pod
metadata:
  labels:
    run: hello-docker
  name: hello-docker
  namespace: challange
spec:
  containers:
  - image: harik8/hello-docker
    name: hello-docker
    ports: 
      - name: hello-docker
        containerPort: 80
        protocol: TCP
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
